from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
import os
from datetime import datetime

def generate_pdf_report(result, original_image_path, heatmap_image_path, output_pdf_path):
    """
    Generates a professional PDF report for the Brain Tumor Analysis.
    """
    doc = SimpleDocTemplate(output_pdf_path, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor("#1b4d7a"),
        alignment=1, # Center
        spaceAfter=20
    )
    story.append(Paragraph("Comprehensive Diagnostic Report: Brain Tumor Analysis", title_style))

    story.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
    story.append(Paragraph("<b>Status:</b> Completed", styles['Normal']))
    story.append(Spacer(1, 12))

    summary_data = [
        ["Tumor Type", result['tumor_type']],
        ["Model Confidence", result['confidence']],
        ["Analysis Outcome", "Detected" if "No" not in result['tumor_type'] else "Normal"]
    ]
    summary_table = Table(summary_data, colWidths=[150, 300])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor("#f2f2f2")),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('PADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 24))

    story.append(Paragraph("<b>Visual Diagnostic Evidence</b>", styles['Heading2']))
    story.append(Spacer(1, 12))

    img_width = 250
    img_height = 250 
    
    img1 = Image(original_image_path, width=img_width, height=img_height)
    img2 = Image(heatmap_image_path, width=img_width, height=img_height)
    
    img_table_data = [[img1, img2], ["Original MRI Scan", "Highlighted Region Analysis"]]
    img_table = Table(img_table_data, colWidths=[img_width + 20, img_width + 20])
    img_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTSIZE', (0, 1), (-1, 1), 10),
        ('TEXTCOLOR', (0, 1), (-1, 1), colors.grey),
    ]))
    story.append(img_table)
    story.append(Spacer(1, 24))

    story.append(Paragraph("<b>Detailed Clinical Analysis</b>", styles['Heading2']))
    story.append(Paragraph(f"<b>Description:</b> {result['description']}", styles['Normal']))
    story.append(Spacer(1, 12))
    story.append(Paragraph(f"<b>Medical Suggestion:</b> {result['suggestion']}", styles['Normal']))
    story.append(Spacer(1, 36))

    disclaimer_style = ParagraphStyle('Disclaimer', parent=styles['Normal'], fontSize=8, textColor=colors.grey, leading=10)
    story.append(Paragraph("<b>DISCLAIMER:</b> This report is generated by a computer-aided diagnostic system for support purposes only. It is not a clinical diagnosis. The automated analysis should be verified by a certified medical professional or radiologist before any treatment decisions.", disclaimer_style))

    doc.build(story)
    return output_pdf_path
